<<<<<<< HEAD
server:
  port: 80

my:
  ds:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: 123456
=======
spring:
  profiles:
    active: common,team

---
spring:
  profiles: common
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource



server:
  port: 80




>>>>>>> 1023ac2bdf72d30c8e853f5f3e1c340fb64fd3e2
