spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 80


upload:
  path: target/classes/static/image/
  hostAddress: null

#mall:
#  aliyun:
#    access-key-id: LTAI4Fr5gfYhcVjLMqeRGbuT
#    access-secret: IrkcHu6dZyrjPZRushgO76P5392HJ1
#    oss:
#      bucket: cskaoyan
#      end-point: oss-sn-beijing.aliyuncs.com
#    sms:
#      region-id: cn-hangzhou
#      template-code: SMS_173765187
#      sign-name: 王道训练营
