spring:
  profiles:
    active: team
  servlet:
    multipart:
      max-file-size: 5242880
      max-request-size: 52428800

pagehelper:
  helper-dialect: mysql

server:
  port: 80
mybatis:
  type-handlers-package: com.cskaoyan.mall.admin.mybatis


logging:
  level:
    com:
      cskaoyan:
        mall:
          admin:
            mapper: debug
