spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


server:
  port: 80


upload:
  path: target/classes/static/image/
  hostAddress: null
